name = "backend"
compatibility_date = "2023-12-01"

[vars]
# GEMINI_API_KEY=""
# DATABASE_URL=""
# DIRECT_DATABASE_URL=""
# SUPABASE_JWT_SECRET=""
# SUPABASE_URL=""
# SUPABASE_ANON_KEY=""
GEMINI_API_KEY="AIzaSyA7NwFwrGCN0SpwqiGjVQ03GRZEZ_XcmKA"

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFKVlo0S0JUSE1INlpBU0NIUVIyUFczQ1IiLCJ0ZW5hbnRfaWQiOiJhMjI3NDkyOGQ3MGNiYzYwMmJhMDVhNTZiZjAzYzI1MjM2YzYyZDZlOGExNDU1MTQ0YjIxMmNlMmQwMTA4YjdhIiwiaW50ZXJuYWxfc2VjcmV0IjoiMTE1OTcwNmQtNjNmZi00YzFjLWI0ODUtOTg3MDA5ODA2M2Q5In0.-fWzH1np7gk2hWVV-H3oc3yuG_0oUUreC9QsKAvRkhk"

DIRECT_DATABASE_URL="postgresql://postgres.jthhoaqaiwzjsfnpvfuy:HK6ZoVfLHpi0KD0I@aws-0-ap-south-1.pooler.supabase.com:5432/postgres"

SUPABASE_JWT_SECRET="ZKp3tSG9jrsc+Zq463RHvjDyVWC0jtOZ5tav70LcIZ0uwaL9nkXlTq4j5qRxXVnBo2CD1LERiraJVEIHu5OpfQ=="

SUPABASE_URL="https://jthhoaqaiwzjsfnpvfuy.supabase.co"

SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0aGhvYXFhaXd6anNmbnB2ZnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTQ4NzQsImV4cCI6MjA2MjAzMDg3NH0.rKyiCMXgKjQicBRpoGuXfYzz42ATfThhMcIBPxkHivk"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"